Repositories:
  - BaseUrl: dp.apps.rancher.io/containers
    Registry: dp.apps.rancher.io
    Username: '{{ env "APPCO_USERNAME" }}'
    Password: '{{ env "APPCO_PASSWORD" }}'
  - BaseUrl: docker.io/rancher
    Target: true
    Registry: docker.io
    Username: '{{ env "DOCKER_USERNAME" }}'
    Password: '{{ env "DOCKER_PASSWORD" }}'
  - BaseUrl: ghcr.io/adamkpickering
    Target: true
    Registry: ghcr.io/adamkpickering
    Username: '{{ env "GHCR_USERNAME" }}'
    Password: '{{ env "GHCR_PASSWORD" }}'
Images:
  - SourceImage: dp.apps.rancher.io/containers/openjdk
    TargetImageName: appco-testtest-containers-openjdk
    Tags:
      - 21.0.6-build7-14.12
      - 21.0.5-build11-12.20
  - SourceImage: rancher/fleet
    Tags:
      - v0.12.0
      - v0.11.5
