version: "2"
linters:
  exclusions:
    rules:
      - linters:
          - errcheck
        source: 'defer fd.Close\(\)'
      - linters:
          - errcheck
        source: 'defer resp.Body.Close\(\)'
      - linters:
          - errcheck
        source: 'defer exec.Command\("helm", "repo", "remove", helmRepoName\).Run\(\)'
