name: Autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
      with:
        go-version: '1.24'

    - name: Build Go script
      run: scripts/build-tools.sh

    - name: Run autoupdate
      run: bin/image-mirror-tools autoupdate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
